### ISSUE TITLE
Latios 0.15.0 throws errors with LATIOS_TRANSFORMS_UNITY

### ISSUE THREAD

**Issue by Miskinis** [Dreaming381/Latios-Framework#71]
After upgrading from 0.14.15 to 0.15.0 I got compile errors in my project on Unity 6000.3.8f1, URP Vulkan, Ubuntu 24.04.4.

I made a fork, maybe it helps [https://github.com/Miskinis/Latios-Framework](https://github.com/Miskinis/Latios-Framework). But it's only for the compile errors. I did try to reimport the project multiple times.

Here are my script defines:
```
UNITY_BURST_EXPERIMENTAL_ATOMIC_INTRINSICS;
ENTITY_STORE_V1;
LATIOS_TRANSFORMS_UNITY;
ENABLE_CONTENT_DELIVERY;
ENABLE_CONTENT_DIAGNOSTICS;
ENABLE_CONTENT_BUILD_DIAGNOSTICS;
DOTS_INSTANCING_ON
```

<details>
<summary>Logs:</summary>

```
Library/PackageCache/com.latios.latiosframework@e3dcd141e5f9/Transforms/Abstract/WorldTransformAspects.cs(22,49): error CS0103: The name 'localToWorld' does not exist in the current context

Library/PackageCache/com.latios.latiosframework@e3dcd141e5f9/Transforms/Abstract/WorldTransformAspects.cs(23,46): error CS1061: 'float4x4' does not contain a definition for 'Translation' and no accessible extension method 'Translation' accepting a first argument of type 'float4x4' could be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.latios.latiosframework@e3dcd141e5f9/Transforms/Abstract/WorldTransformAspects.cs(23,65): error CS1061: 'float4x4' does not contain a definition for 'Rotation' and no accessible extension method 'Rotation' accepting a first argument of type 'float4x4' could be found (are you missing a using directive or an assembly reference?)

Library/PackageCache/com.latios.latiosframework@e3dcd141e5f9/Transforms/Abstract/WorldTransformAspects.cs(23,81): error CS1501: No overload for method 'Scale' takes 0 arguments

Library/PackageCache/com.latios.latiosframework@e3dcd141e5f9/Transforms/Abstract/WorldTransformAspects.cs(27,39): error CS0103: The name 'localToWorld' does not exist in the current context

Library/PackageCache/com.latios.latiosframework@e3dcd141e5f9/Transforms/Abstract/WorldTransformAspects.cs(28,35): error CS0103: The name 'localToWorld' does not exist in the current context

Library/PackageCache/com.latios.latiosframework@e3dcd141e5f9/Transforms/Abstract/WorldTransformAspects.cs(31,38): error CS0103: The name 'localToWorld' does not exist in the current context
```
</details> 

I also get spammed with Kinemation runtime errors in playmode. I tried reimporting all assets and rebuild my singular subscene that contains simple shapes with plain regular MeshRenderer and BoxCollider components, but nothing helped.

<details>
<summary>Logs:</summary>

```
The CullingComputeDispatch expected state does not match the current state. Behavior may not be correct.
UnityEngine.Debug:LogError (object)
Latios.Kinemation.CullingComputeDispatchData`2<Latios.Kinemation.Systems.UploadMaterialPropertiesSystem/CollectState, Latios.Kinemation.Systems.UploadMaterialPropertiesSystem/WriteState>:DoUpdate<Latios.Kinemation.Systems.UploadMaterialPropertiesSystem> (Unity.Entities.SystemState&,Latios.Kinemation.Systems.UploadMaterialPropertiesSystem&) (at ./Packages/com.latios.latiosframework/Kinemation/Systems/Culling/CullingComputeDispatchUnmanagedBase.cs:79)
Latios.Kinemation.Systems.UploadMaterialPropertiesSystem:OnUpdate (Unity.Entities.SystemState&) (at ./Packages/com.latios.latiosframework/Kinemation/Systems/Culling/UploadMaterialPropertiesSystem.cs:106)
Latios.Kinemation.Systems.UploadMaterialPropertiesSystem/Latios.Kinemation.Systems.__codegen__OnUpdate_00000372$BurstDirectCall:Invoke (intptr,intptr)
Latios.Kinemation.Systems.UploadMaterialPropertiesSystem:__codegen__OnUpdate (intptr,intptr)
Unity.Entities.SystemBaseRegistry:ForwardToManaged (intptr,Unity.Entities.SystemState*,void*) (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/SystemBaseRegistry.cs:364)
Unity.Entities.SystemBaseRegistry:CallForwardingFunction (Unity.Entities.SystemState*,Unity.Entities.UnmanagedSystemFunctionType) (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/SystemBaseRegistry.cs:333)
Unity.Entities.SystemBaseRegistry:CallOnUpdate (Unity.Entities.SystemState*) (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/SystemBaseRegistry.cs:376)
Unity.Entities.WorldUnmanagedImpl/Unity.Entities.UnmanagedUpdate_00001698$BurstDirectCall:Invoke (void*)
Unity.Entities.WorldUnmanagedImpl:UnmanagedUpdate (void*)
Unity.Entities.WorldUnmanagedImpl:UpdateSystem (Unity.Entities.SystemHandle) (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/WorldUnmanaged.cs:923)
Unity.Entities.SystemHandle:Update (Unity.Entities.WorldUnmanaged) (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/WorldUnmanaged.cs:166)
Unity.Entities.Exposed.ComponentSystemGroupExposed:UpdateWithTracing (Unity.Entities.SystemHandle,Unity.Entities.SystemState&,Unity.Entities.WorldUnmanaged,Unity.Entities.Exposed.ComponentSystemGroupTracing) (at ./Packages/com.latios.latiosframework/EntitiesExposed/ComponentSystemGroupExposed.cs:33)
Latios.SuperSystem:UpdateUnmanagedSystem (Latios.LatiosWorldUnmanagedImpl*,Unity.Entities.SystemHandle,Unity.Entities.Exposed.ComponentSystemGroupTracing) (at ./Packages/com.latios.latiosframework/Core/Framework/SuperSystem.cs:302)
Latios.SuperSystem:DoLatiosFrameworkComponentSystemGroupUpdate (Unity.Entities.ComponentSystemGroup) (at ./Packages/com.latios.latiosframework/Core/Framework/SuperSystem.cs:222)
Unity.Entities.ComponentSystemGroup:RunDelegateOrDefaultLatiosInjected () (at ./Packages/com.latios.latiosframework/EntitiesExposed/ComponentSystemGroupExposed.cs:144)
Unity.Entities.ComponentSystemGroup:OnUpdate () (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/ComponentSystemGroup.cs:685)
Latios.Kinemation.Systems.CustomGraphicsRoundRobinDispatchSuperSystem:OnUpdate () (at ./Packages/com.latios.latiosframework/Kinemation/Systems/KinemationSuperSystems.cs:178)
Unity.Entities.SystemBase:Update () (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/SystemBase.cs:417)
Unity.Entities.Exposed.ComponentSystemGroupExposed:UpdateWithTracing (Unity.Entities.ComponentSystemBase,Unity.Entities.Exposed.ComponentSystemGroupTracing) (at ./Packages/com.latios.latiosframework/EntitiesExposed/ComponentSystemGroupExposed.cs:43)
Latios.SuperSystem:UpdateManagedSystem (Latios.LatiosWorldUnmanagedImpl*,Unity.Entities.ComponentSystemBase,Unity.Entities.Exposed.ComponentSystemGroupTracing) (at ./Packages/com.latios.latiosframework/Core/Framework/SuperSystem.cs:327)
Latios.SuperSystem:DoLatiosFrameworkComponentSystemGroupUpdate (Unity.Entities.ComponentSystemGroup) (at ./Packages/com.latios.latiosframework/Core/Framework/SuperSystem.cs:227)
Unity.Entities.ComponentSystemGroup:RunDelegateOrDefaultLatiosInjected () (at ./Packages/com.latios.latiosframework/EntitiesExposed/ComponentSystemGroupExposed.cs:144)
Unity.Entities.ComponentSystemGroup:OnUpdate () (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/ComponentSystemGroup.cs:685)
Latios.Kinemation.Systems.KinemationPostRenderWriteSuperSystem:OnUpdate () (at ./Packages/com.latios.latiosframework/Kinemation/Systems/KinemationSuperSystems.cs:127)
Unity.Entities.SystemBase:Update () (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/SystemBase.cs:417)
Unity.Entities.Exposed.ComponentSystemGroupExposed:UpdateWithTracing (Unity.Entities.ComponentSystemBase,Unity.Entities.Exposed.ComponentSystemGroupTracing) (at ./Packages/com.latios.latiosframework/EntitiesExposed/ComponentSystemGroupExposed.cs:43)
Latios.SuperSystem:UpdateManagedSystem (Latios.LatiosWorldUnmanagedImpl*,Unity.Entities.ComponentSystemBase,Unity.Entities.Exposed.ComponentSystemGroupTracing) (at ./Packages/com.latios.latiosframework/Core/Framework/SuperSystem.cs:327)
Latios.SuperSystem:DoLatiosFrameworkComponentSystemGroupUpdate (Unity.Entities.ComponentSystemGroup) (at ./Packages/com.latios.latiosframework/Core/Framework/SuperSystem.cs:227)
Unity.Entities.ComponentSystemGroup:RunDelegateOrDefaultLatiosInjected () (at ./Packages/com.latios.latiosframework/EntitiesExposed/ComponentSystemGroupExposed.cs:144)
Unity.Entities.ComponentSystemGroup:OnUpdate () (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/ComponentSystemGroup.cs:685)
Unity.Entities.SystemBase:Update () (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/SystemBase.cs:417)
Unity.Entities.ScriptBehaviourUpdateOrder/DummyDelegateWrapper:TriggerUpdate () (at ./Library/PackageCache/com.unity.entities@8cc175c78756/Unity.Entities/ScriptBehaviourUpdateOrder.cs:523)
```
</details>

**Comment by Dreaming381** [comment]
Hi! Thanks for reporting!

Your fork has the correct fixes for Unity Transforms. Feel free to make a pull request if you'd like git credit, otherwise I can patch those changes in myself.

As for the log message, it looks like I have a regression for the injection workflow. The fix is to add [DisableAutoCreation] for all systems inside KinemationSuperSystems.cs.

**Comment by Dreaming381** [comment]
Fixed in 0.15.1
